name: drupal-scaffold
recipe: drupal8
config:
  webroot: web #@docroot
  php: 7.2
  via: nginx
  drush: ^8
  xdebug: false
env_file:
  - .env/drupal.env
  - .env/private.env
proxy:
  mannequin:
    - mannequin.lndo.site
services:
  appserver:
    build:
      - composer install
    config:
      conf: .lando/init/php.ini
    build_as_root:
      - .lando/init/terminus.sh
      - .lando/init/blackfire.sh
    run_as_root:
      # TODO: This doesn't seem to run at the correct time to ensure that blackfire-agent is running after a service rebuild.
      - "/etc/init.d/blackfire-agent restart"
  node:
    type: node
    build:
      - yarn install
    globals:
      gulp-cli: latest
  mannequin:
    type: compose
    services:
      image: devwithlando/php:7.3-apache
      command: docker-php-entrypoint /app/vendor/bin/mannequin start -c /app/.mannequin.php *:80
tooling:
  gulp:
    service: node
  yarn:
    service: node
  npm:
    service: node
    cmd: "echo 'NPM is disabled in favor of yarn'"
  behat:
    service: appserver
    cmd: vendor/bin/behat
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
  phpcs:
    service: appserver
    cmd: vendor/bin/phpcs
  eslint:
    service: node
    cmd: node_modules/.bin/eslint
  terminus:
    service: appserver
  latest_db_pantheon:
    service: appserver
    description: Updates the database from the latest Pantheon backup
    cmd: bin/refresh-local-pantheon
  blackfire:
    service: appserver
    user: root
