name: drupal-scaffold
recipe: drupal8
config:
  webroot: web #@docroot
  php: 7.2
  via: nginx
  drush: ^8
  xdebug: false
env_file:
  - .env/drupal.env
  - .env/private.env
proxy:
  mannequin:
    - mannequin.lndo.site
services:
  appserver:
    build:
      - composer install
    build_as_root:
      - wget https://github.com/pantheon-systems/terminus/releases/download/2.3.0/terminus.phar -O /usr/local/bin/terminus
      - chmod +x /usr/local/bin/terminus
      - '[ -z "$TERMINUS_MACHINE_TOKEN" ] && echo "Terminus machine token not set" || terminus auth:login --machine-token=$TERMINUS_MACHINE_TOKEN'
  node:
    type: node
    build:
      - yarn install
    globals:
      gulp-cli: latest
  mannequin:
    type: compose
    services:
      image: devwithlando/php:7.3-apache
      command: docker-php-entrypoint /app/vendor/bin/mannequin start -c /app/.mannequin.php *:80
tooling:
  gulp:
    service: node
  yarn:
    service: node
  npm:
    service: node
    cmd: "echo 'NPM is disabled in favor of yarn'"
  behat:
    service: appserver
    cmd: vendor/bin/behat
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
  phpcs:
    service: appserver
    cmd: vendor/bin/phpcs
  eslint:
    service: node
    cmd: node_modules/.bin/eslint
  terminus:
    service: appserver
  latest_db_pantheon:
    service: appserver
    description: Updates the database from the latest Pantheon backup
    cmd: bin/refresh-local-pantheon
