name: drupal-scaffold
recipe: drupal8
config:
  webroot: web #@docroot
  php: 7.2
  via: nginx
  drush: ^8
  xdebug: false
proxy:
  mannequin:
    - mannequin.lndo.site
services:
  appserver:
    build:
      - composer install
  node:
    type: node
    build:
      - yarn install
    globals:
      gulp-cli: latest
  mannequin:
    type: compose
    services:
      image: devwithlando/php:7.3-apache
      command: docker-php-entrypoint /app/vendor/bin/mannequin start -c /app/.mannequin.php *:80
tooling:
  gulp:
    service: node
  yarn:
    service: node
  npm:
    service: node
    cmd: "echo 'NPM is disabled in favor of yarn'"
  behat:
    service: appserver
    cmd: vendor/bin/behat
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
  phpcs:
    service: appserver
    cmd: vendor/bin/phpcs
  eslint:
    service: node
    cmd: node_modules/.bin/eslint
