# This is a Drupal console "chain" file.
#
# It is used to define a group of console commands you want to run in succession. It can be used to
# prepare an existing site (if you have imported a database), or to install Drupal from scratch.
commands:
# Install Drupal
  - command: site:install
    options:
      uri: http://default/
      force: true
    arguments:
      profile: minimal
  - command: theme:install
    options:
      set-default: true
      uri: http://default/
    arguments:
      theme: [scaffold]
