<?php

/**
 * @file
 * Pattern library module hooks.
 */

/**
 * Implements hook_theme().
 */
function pattern_lib_theme() {
  return [
    'pattern' => [
      'render element' => 'element',
    ],
    'pattern_list' => [
      'variables' => [
        'patterns' => [],
        'renderPatterns' => TRUE,
      ],
    ],
  ];
}

/**
 * Prepares variables for the template.
 */
function template_preprocess_pattern(&$variables) {
  $element = $variables['element'];
  $variables['children'] = $element['#children'];
}
